### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by TheUtopianPlayz** [RealYXNG/DeathHead#2]
add a way to get the players skin on the head, u would probs have to change the head to a custom item and rip the head off of the players skin and then use it as the skin for the custom item, but it would make the plugin amazing a ton of people would love it, some plugins that give the players head with there skin on it already exist they just dont have it drop like urs does ect, so maybe u can look at those for inspiration or examples

**Comment by RealYXNG** [comment]
After looking into it, it's not possible to do that and the reason is you can't change a item texture unless you use a texture pack and it's easy to add a image/texture into a texture pack but it won't update unless you restart the server and players would have to re-download the pack every time. If a player dies for the first time then his head texture won't be shown unless you restart the server and so on.
